# Generated by Django 5.0.9 on 2024-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=123, max_length=100),
        ),
    ]
