# Generated by Django 5.0.9 on 2024-11-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="password", max_length=100),
        ),
    ]
