# Generated by Django 5.0.9 on 2024-11-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0004_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="flashcards.user",
            ),
        ),
    ]
