# Generated by Django 5.0.9 on 2024-11-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0005_flashcardset_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcardset",
            name="cards",
        ),
        migrations.AddField(
            model_name="flashcardset",
            name="cards",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="flashcards.flashcard",
            ),
        ),
    ]
