# Generated by Django 5.0.9 on 2024-11-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0006_remove_flashcardset_cards_flashcardset_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcardset",
            name="comments",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="flashcards.comment",
            ),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
