# Generated by Django 5.0.9 on 2024-11-15 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0007_alter_flashcardset_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcardset",
            name="cards",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="flashcards.flashcard",
            ),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flashcards.comment",
            ),
        ),
    ]
