# Generated by Django 5.0.9 on 2024-11-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0008_alter_flashcardset_cards_alter_flashcardset_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcardset",
            name="comments",
        ),
        migrations.AddField(
            model_name="comment",
            name="flashcardset",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flashcards.flashcardset",
            ),
        ),
    ]
