# Generated by Django 5.0.9 on 2024-11-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0009_remove_flashcardset_comments_comment_flashcardset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcardset",
            name="cards",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="flashcardset",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flashcards.flashcardset",
            ),
        ),
    ]
