# Generated by Django 5.0.9 on 2024-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0011_remove_collection_set_collection_flashcardset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
