# Generated by Django 5.0.9 on 2024-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0013_alter_collection_author_alter_collection_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("Easy", "E"), ("Medium", "M"), ("Hard", "H")],
                default=None,
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
